apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    creationTimestamp: "2026-05-21T11:50:04Z"
    generation: 78
    name: nginx-test
    namespace: argocd
    resourceVersion: "25711"
    uid: a46210a9-fe3a-4d54-8179-185e9f380aa5
  spec:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: apps/nginx
      repoURL: https://github.com/fatimaezzahra123-wq/k8s-devsecops.git
    syncPolicy:
      automated:
        allowEmpty: false
        prune: false
        selfHeal: false
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2026-05-21T11:50:39Z"
      status: Healthy
    history:
    - deployStartedAt: "2026-05-21T11:50:17Z"
      deployedAt: "2026-05-21T11:50:17Z"
      id: 0
      initiatedBy:
        automated: true
      revision: 499cc7aa330f4e77ba7b424d26bee247d7a648f7
      source:
        path: apps/nginx
        repoURL: https://github.com/fatimaezzahra123-wq/k8s-devsecops.git
    operationState:
      finishedAt: "2026-05-21T11:50:17Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          limit: 5
        sync:
          revision: 499cc7aa330f4e77ba7b424d26bee247d7a648f7
          source:
            path: apps/nginx
            repoURL: https://github.com/fatimaezzahra123-wq/k8s-devsecops.git
      phase: Succeeded
      startedAt: "2026-05-21T11:50:17Z"
      syncResult:
        resources:
        - group: apps
          hookPhase: Running
          images:
          - nginx:latest
          kind: Deployment
          message: deployment.apps/nginx-test created
          name: nginx-test
          namespace: default
          status: Synced
          syncPhase: Sync
          version: v1
        revision: 499cc7aa330f4e77ba7b424d26bee247d7a648f7
        source:
          path: apps/nginx
          repoURL: https://github.com/fatimaezzahra123-wq/k8s-devsecops.git
    reconciledAt: "2026-05-21T15:39:34Z"
    resourceHealthSource: appTree
    resources:
    - group: apps
      kind: Deployment
      name: nginx-test
      namespace: default
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Directory
    summary:
      images:
      - nginx:latest
    sync:
      comparedTo:
        destination:
          namespace: default
          server: https://kubernetes.default.svc
        source:
          path: apps/nginx
          repoURL: https://github.com/fatimaezzahra123-wq/k8s-devsecops.git
      revision: e7bcbf9df6185be09cfeb129580c6dd442b1434c
      status: Synced
kind: List
metadata:
  resourceVersion: ""
